language: java
jdk:
  - oraclejdk11
sudo: false
script: mvn install -B -V
after_success: mvn javadoc:javadoc

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: target/javadoc
  github-token: $DEPLOYMENT_TOKEN
  keep-history: true
  on:
    branch: master
